main:
	g++ -std=c++11 -o main main.cpp simulation.cpp event.cpp customer.cpp exponential_random_number.cpp simulation_log.cpp event_record.cpp customer_record.cpp server.cpp

clean:
	rm main.o simulation.o event.o customer.o exponential_random_number.o simulation_log.o event_record.o customer_record.o

